[theme]
base = "light"
primaryColor = "#2A9D8F"                  
backgroundColor = "#FAFAF7"               
secondaryBackgroundColor = "#EAEAEA"      
textColor = "#1D1D1F"                     
font = "sans serif"
